kind: pipeline
type: docker
name: cicd

steps:
- name: test
  image: python:3.6
  commands:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - pip install docker-compose
  - docker-compose run app sh -c "python manage.py test && flake8"
