kind: pipeline
type: docker
name: default

steps:
- name: default
  image: docker/compose
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - docker-compose -f docker-compose.drone.yml build --force-rm --no-cache
  - docker-compose -f docker-compose.drone.yml run --rm app sh -c "python manage.py test && flake8"

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
